fix(setup-dotfiles/pre/50-linux-deps): exit on failure

diff --git a/.config/setup-dotfiles/pre/50-linux-deps b/.config/setup-dotfiles/pre/50-linux-deps
--- a/.config/setup-dotfiles/pre/50-linux-deps
+++ b/.config/setup-dotfiles/pre/50-linux-deps
@@ -26,7 +26,7 @@ check_availability() {
   exit
 }
 
-if printf "%s" "$required" | check_availability error "required but not available"; then
+if ! printf "%s" "$required" | check_availability error "required but not available"; then
   error_exit "stopped"
 fi
 
